# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/viewtouch/viewtouch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/viewtouch/viewtouch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/viewtouch/viewtouch/CMakeFiles /home/viewtouch/viewtouch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/viewtouch/viewtouch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GenerateBuildNumber

# Build rule for target.
GenerateBuildNumber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenerateBuildNumber
.PHONY : GenerateBuildNumber

# fast build rule for target.
GenerateBuildNumber/fast:
	$(MAKE) -f CMakeFiles/GenerateBuildNumber.dir/build.make CMakeFiles/GenerateBuildNumber.dir/build
.PHONY : GenerateBuildNumber/fast

#=============================================================================
# Target rules for targets named conf_file

# Build rule for target.
conf_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conf_file
.PHONY : conf_file

# fast build rule for target.
conf_file/fast:
	$(MAKE) -f CMakeFiles/conf_file.dir/build.make CMakeFiles/conf_file.dir/build
.PHONY : conf_file/fast

#=============================================================================
# Target rules for targets named vt_cdu

# Build rule for target.
vt_cdu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vt_cdu
.PHONY : vt_cdu

# fast build rule for target.
vt_cdu/fast:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/build
.PHONY : vt_cdu/fast

#=============================================================================
# Target rules for targets named vt_main

# Build rule for target.
vt_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vt_main
.PHONY : vt_main

# fast build rule for target.
vt_main/fast:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/build
.PHONY : vt_main/fast

#=============================================================================
# Target rules for targets named vt_print

# Build rule for target.
vt_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vt_print
.PHONY : vt_print

# fast build rule for target.
vt_print/fast:
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/build
.PHONY : vt_print/fast

#=============================================================================
# Target rules for targets named vt_temphash

# Build rule for target.
vt_temphash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vt_temphash
.PHONY : vt_temphash

# fast build rule for target.
vt_temphash/fast:
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/build
.PHONY : vt_temphash/fast

#=============================================================================
# Target rules for targets named vt_term

# Build rule for target.
vt_term: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vt_term
.PHONY : vt_term

# fast build rule for target.
vt_term/fast:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/build
.PHONY : vt_term/fast

#=============================================================================
# Target rules for targets named vtpos

# Build rule for target.
vtpos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vtpos
.PHONY : vtpos

# fast build rule for target.
vtpos/fast:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/build
.PHONY : vtpos/fast

#=============================================================================
# Target rules for targets named zone

# Build rule for target.
zone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zone
.PHONY : zone

# fast build rule for target.
zone/fast:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/build
.PHONY : zone/fast

cdu/cdu_main.o: cdu/cdu_main.cc.o
.PHONY : cdu/cdu_main.o

# target to build an object file
cdu/cdu_main.cc.o:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/cdu/cdu_main.cc.o
.PHONY : cdu/cdu_main.cc.o

cdu/cdu_main.i: cdu/cdu_main.cc.i
.PHONY : cdu/cdu_main.i

# target to preprocess a source file
cdu/cdu_main.cc.i:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/cdu/cdu_main.cc.i
.PHONY : cdu/cdu_main.cc.i

cdu/cdu_main.s: cdu/cdu_main.cc.s
.PHONY : cdu/cdu_main.s

# target to generate assembly for a file
cdu/cdu_main.cc.s:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/cdu/cdu_main.cc.s
.PHONY : cdu/cdu_main.cc.s

conf_file.o: conf_file.cc.o
.PHONY : conf_file.o

# target to build an object file
conf_file.cc.o:
	$(MAKE) -f CMakeFiles/conf_file.dir/build.make CMakeFiles/conf_file.dir/conf_file.cc.o
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/conf_file.cc.o
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/conf_file.cc.o
.PHONY : conf_file.cc.o

conf_file.i: conf_file.cc.i
.PHONY : conf_file.i

# target to preprocess a source file
conf_file.cc.i:
	$(MAKE) -f CMakeFiles/conf_file.dir/build.make CMakeFiles/conf_file.dir/conf_file.cc.i
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/conf_file.cc.i
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/conf_file.cc.i
.PHONY : conf_file.cc.i

conf_file.s: conf_file.cc.s
.PHONY : conf_file.s

# target to generate assembly for a file
conf_file.cc.s:
	$(MAKE) -f CMakeFiles/conf_file.dir/build.make CMakeFiles/conf_file.dir/conf_file.cc.s
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/conf_file.cc.s
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/conf_file.cc.s
.PHONY : conf_file.cc.s

data_file.o: data_file.cc.o
.PHONY : data_file.o

# target to build an object file
data_file.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/data_file.cc.o
.PHONY : data_file.cc.o

data_file.i: data_file.cc.i
.PHONY : data_file.i

# target to preprocess a source file
data_file.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/data_file.cc.i
.PHONY : data_file.cc.i

data_file.s: data_file.cc.s
.PHONY : data_file.s

# target to generate assembly for a file
data_file.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/data_file.cc.s
.PHONY : data_file.cc.s

debug.o: debug.cc.o
.PHONY : debug.o

# target to build an object file
debug.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/debug.cc.o
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/debug.cc.o
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/debug.cc.o
.PHONY : debug.cc.o

debug.i: debug.cc.i
.PHONY : debug.i

# target to preprocess a source file
debug.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/debug.cc.i
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/debug.cc.i
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/debug.cc.i
.PHONY : debug.cc.i

debug.s: debug.cc.s
.PHONY : debug.s

# target to generate assembly for a file
debug.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/debug.cc.s
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/debug.cc.s
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/debug.cc.s
.PHONY : debug.cc.s

external/blowfish.o: external/blowfish.c.o
.PHONY : external/blowfish.o

# target to build an object file
external/blowfish.c.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/blowfish.c.o
.PHONY : external/blowfish.c.o

external/blowfish.i: external/blowfish.c.i
.PHONY : external/blowfish.i

# target to preprocess a source file
external/blowfish.c.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/blowfish.c.i
.PHONY : external/blowfish.c.i

external/blowfish.s: external/blowfish.c.s
.PHONY : external/blowfish.s

# target to generate assembly for a file
external/blowfish.c.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/blowfish.c.s
.PHONY : external/blowfish.c.s

external/sha1.o: external/sha1.cc.o
.PHONY : external/sha1.o

# target to build an object file
external/sha1.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/sha1.cc.o
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/external/sha1.cc.o
.PHONY : external/sha1.cc.o

external/sha1.i: external/sha1.cc.i
.PHONY : external/sha1.i

# target to preprocess a source file
external/sha1.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/sha1.cc.i
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/external/sha1.cc.i
.PHONY : external/sha1.cc.i

external/sha1.s: external/sha1.cc.s
.PHONY : external/sha1.s

# target to generate assembly for a file
external/sha1.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/external/sha1.cc.s
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/external/sha1.cc.s
.PHONY : external/sha1.cc.s

generic_char.o: generic_char.cc.o
.PHONY : generic_char.o

# target to build an object file
generic_char.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/generic_char.cc.o
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/generic_char.cc.o
.PHONY : generic_char.cc.o

generic_char.i: generic_char.cc.i
.PHONY : generic_char.i

# target to preprocess a source file
generic_char.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/generic_char.cc.i
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/generic_char.cc.i
.PHONY : generic_char.cc.i

generic_char.s: generic_char.cc.s
.PHONY : generic_char.s

# target to generate assembly for a file
generic_char.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/generic_char.cc.s
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/generic_char.cc.s
.PHONY : generic_char.cc.s

image_data.o: image_data.cc.o
.PHONY : image_data.o

# target to build an object file
image_data.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/image_data.cc.o
.PHONY : image_data.cc.o

image_data.i: image_data.cc.i
.PHONY : image_data.i

# target to preprocess a source file
image_data.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/image_data.cc.i
.PHONY : image_data.cc.i

image_data.s: image_data.cc.s
.PHONY : image_data.s

# target to generate assembly for a file
image_data.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/image_data.cc.s
.PHONY : image_data.cc.s

loader/loader_main.o: loader/loader_main.cc.o
.PHONY : loader/loader_main.o

# target to build an object file
loader/loader_main.cc.o:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/loader/loader_main.cc.o
.PHONY : loader/loader_main.cc.o

loader/loader_main.i: loader/loader_main.cc.i
.PHONY : loader/loader_main.i

# target to preprocess a source file
loader/loader_main.cc.i:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/loader/loader_main.cc.i
.PHONY : loader/loader_main.cc.i

loader/loader_main.s: loader/loader_main.cc.s
.PHONY : loader/loader_main.s

# target to generate assembly for a file
loader/loader_main.cc.s:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/loader/loader_main.cc.s
.PHONY : loader/loader_main.cc.s

logger.o: logger.cc.o
.PHONY : logger.o

# target to build an object file
logger.cc.o:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/logger.cc.o
.PHONY : logger.cc.o

logger.i: logger.cc.i
.PHONY : logger.i

# target to preprocess a source file
logger.cc.i:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/logger.cc.i
.PHONY : logger.cc.i

logger.s: logger.cc.s
.PHONY : logger.s

# target to generate assembly for a file
logger.cc.s:
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/logger.cc.s
.PHONY : logger.cc.s

main/account.o: main/account.cc.o
.PHONY : main/account.o

# target to build an object file
main/account.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/account.cc.o
.PHONY : main/account.cc.o

main/account.i: main/account.cc.i
.PHONY : main/account.i

# target to preprocess a source file
main/account.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/account.cc.i
.PHONY : main/account.cc.i

main/account.s: main/account.cc.s
.PHONY : main/account.s

# target to generate assembly for a file
main/account.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/account.cc.s
.PHONY : main/account.cc.s

main/archive.o: main/archive.cc.o
.PHONY : main/archive.o

# target to build an object file
main/archive.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/archive.cc.o
.PHONY : main/archive.cc.o

main/archive.i: main/archive.cc.i
.PHONY : main/archive.i

# target to preprocess a source file
main/archive.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/archive.cc.i
.PHONY : main/archive.cc.i

main/archive.s: main/archive.cc.s
.PHONY : main/archive.s

# target to generate assembly for a file
main/archive.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/archive.cc.s
.PHONY : main/archive.cc.s

main/cdu.o: main/cdu.cc.o
.PHONY : main/cdu.o

# target to build an object file
main/cdu.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu.cc.o
.PHONY : main/cdu.cc.o

main/cdu.i: main/cdu.cc.i
.PHONY : main/cdu.i

# target to preprocess a source file
main/cdu.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu.cc.i
.PHONY : main/cdu.cc.i

main/cdu.s: main/cdu.cc.s
.PHONY : main/cdu.s

# target to generate assembly for a file
main/cdu.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu.cc.s
.PHONY : main/cdu.cc.s

main/cdu_att.o: main/cdu_att.cc.o
.PHONY : main/cdu_att.o

# target to build an object file
main/cdu_att.cc.o:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/main/cdu_att.cc.o
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu_att.cc.o
.PHONY : main/cdu_att.cc.o

main/cdu_att.i: main/cdu_att.cc.i
.PHONY : main/cdu_att.i

# target to preprocess a source file
main/cdu_att.cc.i:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/main/cdu_att.cc.i
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu_att.cc.i
.PHONY : main/cdu_att.cc.i

main/cdu_att.s: main/cdu_att.cc.s
.PHONY : main/cdu_att.s

# target to generate assembly for a file
main/cdu_att.cc.s:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/main/cdu_att.cc.s
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/cdu_att.cc.s
.PHONY : main/cdu_att.cc.s

main/chart.o: main/chart.cc.o
.PHONY : main/chart.o

# target to build an object file
main/chart.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/chart.cc.o
.PHONY : main/chart.cc.o

main/chart.i: main/chart.cc.i
.PHONY : main/chart.i

# target to preprocess a source file
main/chart.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/chart.cc.i
.PHONY : main/chart.cc.i

main/chart.s: main/chart.cc.s
.PHONY : main/chart.s

# target to generate assembly for a file
main/chart.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/chart.cc.s
.PHONY : main/chart.cc.s

main/check.o: main/check.cc.o
.PHONY : main/check.o

# target to build an object file
main/check.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/check.cc.o
.PHONY : main/check.cc.o

main/check.i: main/check.cc.i
.PHONY : main/check.i

# target to preprocess a source file
main/check.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/check.cc.i
.PHONY : main/check.cc.i

main/check.s: main/check.cc.s
.PHONY : main/check.s

# target to generate assembly for a file
main/check.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/check.cc.s
.PHONY : main/check.cc.s

main/credit.o: main/credit.cc.o
.PHONY : main/credit.o

# target to build an object file
main/credit.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/credit.cc.o
.PHONY : main/credit.cc.o

main/credit.i: main/credit.cc.i
.PHONY : main/credit.i

# target to preprocess a source file
main/credit.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/credit.cc.i
.PHONY : main/credit.cc.i

main/credit.s: main/credit.cc.s
.PHONY : main/credit.s

# target to generate assembly for a file
main/credit.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/credit.cc.s
.PHONY : main/credit.cc.s

main/customer.o: main/customer.cc.o
.PHONY : main/customer.o

# target to build an object file
main/customer.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/customer.cc.o
.PHONY : main/customer.cc.o

main/customer.i: main/customer.cc.i
.PHONY : main/customer.i

# target to preprocess a source file
main/customer.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/customer.cc.i
.PHONY : main/customer.cc.i

main/customer.s: main/customer.cc.s
.PHONY : main/customer.s

# target to generate assembly for a file
main/customer.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/customer.cc.s
.PHONY : main/customer.cc.s

main/drawer.o: main/drawer.cc.o
.PHONY : main/drawer.o

# target to build an object file
main/drawer.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/drawer.cc.o
.PHONY : main/drawer.cc.o

main/drawer.i: main/drawer.cc.i
.PHONY : main/drawer.i

# target to preprocess a source file
main/drawer.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/drawer.cc.i
.PHONY : main/drawer.cc.i

main/drawer.s: main/drawer.cc.s
.PHONY : main/drawer.s

# target to generate assembly for a file
main/drawer.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/drawer.cc.s
.PHONY : main/drawer.cc.s

main/employee.o: main/employee.cc.o
.PHONY : main/employee.o

# target to build an object file
main/employee.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/employee.cc.o
.PHONY : main/employee.cc.o

main/employee.i: main/employee.cc.i
.PHONY : main/employee.i

# target to preprocess a source file
main/employee.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/employee.cc.i
.PHONY : main/employee.cc.i

main/employee.s: main/employee.cc.s
.PHONY : main/employee.s

# target to generate assembly for a file
main/employee.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/employee.cc.s
.PHONY : main/employee.cc.s

main/exception.o: main/exception.cc.o
.PHONY : main/exception.o

# target to build an object file
main/exception.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/exception.cc.o
.PHONY : main/exception.cc.o

main/exception.i: main/exception.cc.i
.PHONY : main/exception.i

# target to preprocess a source file
main/exception.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/exception.cc.i
.PHONY : main/exception.cc.i

main/exception.s: main/exception.cc.s
.PHONY : main/exception.s

# target to generate assembly for a file
main/exception.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/exception.cc.s
.PHONY : main/exception.cc.s

main/expense.o: main/expense.cc.o
.PHONY : main/expense.o

# target to build an object file
main/expense.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/expense.cc.o
.PHONY : main/expense.cc.o

main/expense.i: main/expense.cc.i
.PHONY : main/expense.i

# target to preprocess a source file
main/expense.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/expense.cc.i
.PHONY : main/expense.cc.i

main/expense.s: main/expense.cc.s
.PHONY : main/expense.s

# target to generate assembly for a file
main/expense.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/expense.cc.s
.PHONY : main/expense.cc.s

main/inventory.o: main/inventory.cc.o
.PHONY : main/inventory.o

# target to build an object file
main/inventory.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/inventory.cc.o
.PHONY : main/inventory.cc.o

main/inventory.i: main/inventory.cc.i
.PHONY : main/inventory.i

# target to preprocess a source file
main/inventory.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/inventory.cc.i
.PHONY : main/inventory.cc.i

main/inventory.s: main/inventory.cc.s
.PHONY : main/inventory.s

# target to generate assembly for a file
main/inventory.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/inventory.cc.s
.PHONY : main/inventory.cc.s

main/labels.o: main/labels.cc.o
.PHONY : main/labels.o

# target to build an object file
main/labels.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labels.cc.o
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/main/labels.cc.o
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/main/labels.cc.o
.PHONY : main/labels.cc.o

main/labels.i: main/labels.cc.i
.PHONY : main/labels.i

# target to preprocess a source file
main/labels.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labels.cc.i
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/main/labels.cc.i
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/main/labels.cc.i
.PHONY : main/labels.cc.i

main/labels.s: main/labels.cc.s
.PHONY : main/labels.s

# target to generate assembly for a file
main/labels.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labels.cc.s
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/main/labels.cc.s
	$(MAKE) -f CMakeFiles/vtpos.dir/build.make CMakeFiles/vtpos.dir/main/labels.cc.s
.PHONY : main/labels.cc.s

main/labor.o: main/labor.cc.o
.PHONY : main/labor.o

# target to build an object file
main/labor.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labor.cc.o
.PHONY : main/labor.cc.o

main/labor.i: main/labor.cc.i
.PHONY : main/labor.i

# target to preprocess a source file
main/labor.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labor.cc.i
.PHONY : main/labor.cc.i

main/labor.s: main/labor.cc.s
.PHONY : main/labor.s

# target to generate assembly for a file
main/labor.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/labor.cc.s
.PHONY : main/labor.cc.s

main/license.o: main/license.cc.o
.PHONY : main/license.o

# target to build an object file
main/license.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license.cc.o
.PHONY : main/license.cc.o

main/license.i: main/license.cc.i
.PHONY : main/license.i

# target to preprocess a source file
main/license.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license.cc.i
.PHONY : main/license.cc.i

main/license.s: main/license.cc.s
.PHONY : main/license.s

# target to generate assembly for a file
main/license.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license.cc.s
.PHONY : main/license.cc.s

main/license_hash.o: main/license_hash.cc.o
.PHONY : main/license_hash.o

# target to build an object file
main/license_hash.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license_hash.cc.o
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/license_hash.cc.o
.PHONY : main/license_hash.cc.o

main/license_hash.i: main/license_hash.cc.i
.PHONY : main/license_hash.i

# target to preprocess a source file
main/license_hash.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license_hash.cc.i
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/license_hash.cc.i
.PHONY : main/license_hash.cc.i

main/license_hash.s: main/license_hash.cc.s
.PHONY : main/license_hash.s

# target to generate assembly for a file
main/license_hash.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/license_hash.cc.s
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/license_hash.cc.s
.PHONY : main/license_hash.cc.s

main/locale.o: main/locale.cc.o
.PHONY : main/locale.o

# target to build an object file
main/locale.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/locale.cc.o
.PHONY : main/locale.cc.o

main/locale.i: main/locale.cc.i
.PHONY : main/locale.i

# target to preprocess a source file
main/locale.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/locale.cc.i
.PHONY : main/locale.cc.i

main/locale.s: main/locale.cc.s
.PHONY : main/locale.s

# target to generate assembly for a file
main/locale.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/locale.cc.s
.PHONY : main/locale.cc.s

main/manager.o: main/manager.cc.o
.PHONY : main/manager.o

# target to build an object file
main/manager.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/manager.cc.o
.PHONY : main/manager.cc.o

main/manager.i: main/manager.cc.i
.PHONY : main/manager.i

# target to preprocess a source file
main/manager.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/manager.cc.i
.PHONY : main/manager.cc.i

main/manager.s: main/manager.cc.s
.PHONY : main/manager.s

# target to generate assembly for a file
main/manager.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/manager.cc.s
.PHONY : main/manager.cc.s

main/printer.o: main/printer.cc.o
.PHONY : main/printer.o

# target to build an object file
main/printer.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/printer.cc.o
.PHONY : main/printer.cc.o

main/printer.i: main/printer.cc.i
.PHONY : main/printer.i

# target to preprocess a source file
main/printer.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/printer.cc.i
.PHONY : main/printer.cc.i

main/printer.s: main/printer.cc.s
.PHONY : main/printer.s

# target to generate assembly for a file
main/printer.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/printer.cc.s
.PHONY : main/printer.cc.s

main/report.o: main/report.cc.o
.PHONY : main/report.o

# target to build an object file
main/report.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/report.cc.o
.PHONY : main/report.cc.o

main/report.i: main/report.cc.i
.PHONY : main/report.i

# target to preprocess a source file
main/report.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/report.cc.i
.PHONY : main/report.cc.i

main/report.s: main/report.cc.s
.PHONY : main/report.s

# target to generate assembly for a file
main/report.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/report.cc.s
.PHONY : main/report.cc.s

main/sales.o: main/sales.cc.o
.PHONY : main/sales.o

# target to build an object file
main/sales.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/sales.cc.o
.PHONY : main/sales.cc.o

main/sales.i: main/sales.cc.i
.PHONY : main/sales.i

# target to preprocess a source file
main/sales.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/sales.cc.i
.PHONY : main/sales.cc.i

main/sales.s: main/sales.cc.s
.PHONY : main/sales.s

# target to generate assembly for a file
main/sales.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/sales.cc.s
.PHONY : main/sales.cc.s

main/settings.o: main/settings.cc.o
.PHONY : main/settings.o

# target to build an object file
main/settings.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/settings.cc.o
.PHONY : main/settings.cc.o

main/settings.i: main/settings.cc.i
.PHONY : main/settings.i

# target to preprocess a source file
main/settings.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/settings.cc.i
.PHONY : main/settings.cc.i

main/settings.s: main/settings.cc.s
.PHONY : main/settings.s

# target to generate assembly for a file
main/settings.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/settings.cc.s
.PHONY : main/settings.cc.s

main/system.o: main/system.cc.o
.PHONY : main/system.o

# target to build an object file
main/system.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system.cc.o
.PHONY : main/system.cc.o

main/system.i: main/system.cc.i
.PHONY : main/system.i

# target to preprocess a source file
main/system.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system.cc.i
.PHONY : main/system.cc.i

main/system.s: main/system.cc.s
.PHONY : main/system.s

# target to generate assembly for a file
main/system.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system.cc.s
.PHONY : main/system.cc.s

main/system_report.o: main/system_report.cc.o
.PHONY : main/system_report.o

# target to build an object file
main/system_report.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_report.cc.o
.PHONY : main/system_report.cc.o

main/system_report.i: main/system_report.cc.i
.PHONY : main/system_report.i

# target to preprocess a source file
main/system_report.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_report.cc.i
.PHONY : main/system_report.cc.i

main/system_report.s: main/system_report.cc.s
.PHONY : main/system_report.s

# target to generate assembly for a file
main/system_report.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_report.cc.s
.PHONY : main/system_report.cc.s

main/system_salesmix.o: main/system_salesmix.cc.o
.PHONY : main/system_salesmix.o

# target to build an object file
main/system_salesmix.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_salesmix.cc.o
.PHONY : main/system_salesmix.cc.o

main/system_salesmix.i: main/system_salesmix.cc.i
.PHONY : main/system_salesmix.i

# target to preprocess a source file
main/system_salesmix.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_salesmix.cc.i
.PHONY : main/system_salesmix.cc.i

main/system_salesmix.s: main/system_salesmix.cc.s
.PHONY : main/system_salesmix.s

# target to generate assembly for a file
main/system_salesmix.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/system_salesmix.cc.s
.PHONY : main/system_salesmix.cc.s

main/temphash.o: main/temphash.cc.o
.PHONY : main/temphash.o

# target to build an object file
main/temphash.cc.o:
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/temphash.cc.o
.PHONY : main/temphash.cc.o

main/temphash.i: main/temphash.cc.i
.PHONY : main/temphash.i

# target to preprocess a source file
main/temphash.cc.i:
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/temphash.cc.i
.PHONY : main/temphash.cc.i

main/temphash.s: main/temphash.cc.s
.PHONY : main/temphash.s

# target to generate assembly for a file
main/temphash.cc.s:
	$(MAKE) -f CMakeFiles/vt_temphash.dir/build.make CMakeFiles/vt_temphash.dir/main/temphash.cc.s
.PHONY : main/temphash.cc.s

main/terminal.o: main/terminal.cc.o
.PHONY : main/terminal.o

# target to build an object file
main/terminal.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/terminal.cc.o
.PHONY : main/terminal.cc.o

main/terminal.i: main/terminal.cc.i
.PHONY : main/terminal.i

# target to preprocess a source file
main/terminal.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/terminal.cc.i
.PHONY : main/terminal.cc.i

main/terminal.s: main/terminal.cc.s
.PHONY : main/terminal.s

# target to generate assembly for a file
main/terminal.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/terminal.cc.s
.PHONY : main/terminal.cc.s

main/tips.o: main/tips.cc.o
.PHONY : main/tips.o

# target to build an object file
main/tips.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/tips.cc.o
.PHONY : main/tips.cc.o

main/tips.i: main/tips.cc.i
.PHONY : main/tips.i

# target to preprocess a source file
main/tips.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/tips.cc.i
.PHONY : main/tips.cc.i

main/tips.s: main/tips.cc.s
.PHONY : main/tips.s

# target to generate assembly for a file
main/tips.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/main/tips.cc.s
.PHONY : main/tips.cc.s

print/print_main.o: print/print_main.cc.o
.PHONY : print/print_main.o

# target to build an object file
print/print_main.cc.o:
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/print/print_main.cc.o
.PHONY : print/print_main.cc.o

print/print_main.i: print/print_main.cc.i
.PHONY : print/print_main.i

# target to preprocess a source file
print/print_main.cc.i:
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/print/print_main.cc.i
.PHONY : print/print_main.cc.i

print/print_main.s: print/print_main.cc.s
.PHONY : print/print_main.s

# target to generate assembly for a file
print/print_main.cc.s:
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/print/print_main.cc.s
.PHONY : print/print_main.cc.s

remote_link.o: remote_link.cc.o
.PHONY : remote_link.o

# target to build an object file
remote_link.cc.o:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/remote_link.cc.o
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/remote_link.cc.o
.PHONY : remote_link.cc.o

remote_link.i: remote_link.cc.i
.PHONY : remote_link.i

# target to preprocess a source file
remote_link.cc.i:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/remote_link.cc.i
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/remote_link.cc.i
.PHONY : remote_link.cc.i

remote_link.s: remote_link.cc.s
.PHONY : remote_link.s

# target to generate assembly for a file
remote_link.cc.s:
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/remote_link.cc.s
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/remote_link.cc.s
.PHONY : remote_link.cc.s

socket.o: socket.cc.o
.PHONY : socket.o

# target to build an object file
socket.cc.o:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/socket.cc.o
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/socket.cc.o
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/socket.cc.o
.PHONY : socket.cc.o

socket.i: socket.cc.i
.PHONY : socket.i

# target to preprocess a source file
socket.cc.i:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/socket.cc.i
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/socket.cc.i
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/socket.cc.i
.PHONY : socket.cc.i

socket.s: socket.cc.s
.PHONY : socket.s

# target to generate assembly for a file
socket.cc.s:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/socket.cc.s
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/socket.cc.s
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/socket.cc.s
.PHONY : socket.cc.s

term/layer.o: term/layer.cc.o
.PHONY : term/layer.o

# target to build an object file
term/layer.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/layer.cc.o
.PHONY : term/layer.cc.o

term/layer.i: term/layer.cc.i
.PHONY : term/layer.i

# target to preprocess a source file
term/layer.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/layer.cc.i
.PHONY : term/layer.cc.i

term/layer.s: term/layer.cc.s
.PHONY : term/layer.s

# target to generate assembly for a file
term/layer.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/layer.cc.s
.PHONY : term/layer.cc.s

term/term_credit.o: term/term_credit.cc.o
.PHONY : term/term_credit.o

# target to build an object file
term/term_credit.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_credit.cc.o
.PHONY : term/term_credit.cc.o

term/term_credit.i: term/term_credit.cc.i
.PHONY : term/term_credit.i

# target to preprocess a source file
term/term_credit.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_credit.cc.i
.PHONY : term/term_credit.cc.i

term/term_credit.s: term/term_credit.cc.s
.PHONY : term/term_credit.s

# target to generate assembly for a file
term/term_credit.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_credit.cc.s
.PHONY : term/term_credit.cc.s

term/term_dialog.o: term/term_dialog.cc.o
.PHONY : term/term_dialog.o

# target to build an object file
term/term_dialog.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_dialog.cc.o
.PHONY : term/term_dialog.cc.o

term/term_dialog.i: term/term_dialog.cc.i
.PHONY : term/term_dialog.i

# target to preprocess a source file
term/term_dialog.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_dialog.cc.i
.PHONY : term/term_dialog.cc.i

term/term_dialog.s: term/term_dialog.cc.s
.PHONY : term/term_dialog.s

# target to generate assembly for a file
term/term_dialog.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_dialog.cc.s
.PHONY : term/term_dialog.cc.s

term/term_main.o: term/term_main.cc.o
.PHONY : term/term_main.o

# target to build an object file
term/term_main.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_main.cc.o
.PHONY : term/term_main.cc.o

term/term_main.i: term/term_main.cc.i
.PHONY : term/term_main.i

# target to preprocess a source file
term/term_main.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_main.cc.i
.PHONY : term/term_main.cc.i

term/term_main.s: term/term_main.cc.s
.PHONY : term/term_main.s

# target to generate assembly for a file
term/term_main.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_main.cc.s
.PHONY : term/term_main.cc.s

term/term_view.o: term/term_view.cc.o
.PHONY : term/term_view.o

# target to build an object file
term/term_view.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_view.cc.o
.PHONY : term/term_view.cc.o

term/term_view.i: term/term_view.cc.i
.PHONY : term/term_view.i

# target to preprocess a source file
term/term_view.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_view.cc.i
.PHONY : term/term_view.cc.i

term/term_view.s: term/term_view.cc.s
.PHONY : term/term_view.s

# target to generate assembly for a file
term/term_view.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/term_view.cc.s
.PHONY : term/term_view.cc.s

term/touch_screen.o: term/touch_screen.cc.o
.PHONY : term/touch_screen.o

# target to build an object file
term/touch_screen.cc.o:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/touch_screen.cc.o
.PHONY : term/touch_screen.cc.o

term/touch_screen.i: term/touch_screen.cc.i
.PHONY : term/touch_screen.i

# target to preprocess a source file
term/touch_screen.cc.i:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/touch_screen.cc.i
.PHONY : term/touch_screen.cc.i

term/touch_screen.s: term/touch_screen.cc.s
.PHONY : term/touch_screen.s

# target to generate assembly for a file
term/touch_screen.cc.s:
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/term/touch_screen.cc.s
.PHONY : term/touch_screen.cc.s

utility.o: utility.cc.o
.PHONY : utility.o

# target to build an object file
utility.cc.o:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/utility.cc.o
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/utility.cc.o
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/utility.cc.o
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/utility.cc.o
.PHONY : utility.cc.o

utility.i: utility.cc.i
.PHONY : utility.i

# target to preprocess a source file
utility.cc.i:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/utility.cc.i
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/utility.cc.i
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/utility.cc.i
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/utility.cc.i
.PHONY : utility.cc.i

utility.s: utility.cc.s
.PHONY : utility.s

# target to generate assembly for a file
utility.cc.s:
	$(MAKE) -f CMakeFiles/vt_cdu.dir/build.make CMakeFiles/vt_cdu.dir/utility.cc.s
	$(MAKE) -f CMakeFiles/vt_main.dir/build.make CMakeFiles/vt_main.dir/utility.cc.s
	$(MAKE) -f CMakeFiles/vt_print.dir/build.make CMakeFiles/vt_print.dir/utility.cc.s
	$(MAKE) -f CMakeFiles/vt_term.dir/build.make CMakeFiles/vt_term.dir/utility.cc.s
.PHONY : utility.cc.s

zone/account_zone.o: zone/account_zone.cc.o
.PHONY : zone/account_zone.o

# target to build an object file
zone/account_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/account_zone.cc.o
.PHONY : zone/account_zone.cc.o

zone/account_zone.i: zone/account_zone.cc.i
.PHONY : zone/account_zone.i

# target to preprocess a source file
zone/account_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/account_zone.cc.i
.PHONY : zone/account_zone.cc.i

zone/account_zone.s: zone/account_zone.cc.s
.PHONY : zone/account_zone.s

# target to generate assembly for a file
zone/account_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/account_zone.cc.s
.PHONY : zone/account_zone.cc.s

zone/button_zone.o: zone/button_zone.cc.o
.PHONY : zone/button_zone.o

# target to build an object file
zone/button_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/button_zone.cc.o
.PHONY : zone/button_zone.cc.o

zone/button_zone.i: zone/button_zone.cc.i
.PHONY : zone/button_zone.i

# target to preprocess a source file
zone/button_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/button_zone.cc.i
.PHONY : zone/button_zone.cc.i

zone/button_zone.s: zone/button_zone.cc.s
.PHONY : zone/button_zone.s

# target to generate assembly for a file
zone/button_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/button_zone.cc.s
.PHONY : zone/button_zone.cc.s

zone/cdu_zone.o: zone/cdu_zone.cc.o
.PHONY : zone/cdu_zone.o

# target to build an object file
zone/cdu_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/cdu_zone.cc.o
.PHONY : zone/cdu_zone.cc.o

zone/cdu_zone.i: zone/cdu_zone.cc.i
.PHONY : zone/cdu_zone.i

# target to preprocess a source file
zone/cdu_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/cdu_zone.cc.i
.PHONY : zone/cdu_zone.cc.i

zone/cdu_zone.s: zone/cdu_zone.cc.s
.PHONY : zone/cdu_zone.s

# target to generate assembly for a file
zone/cdu_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/cdu_zone.cc.s
.PHONY : zone/cdu_zone.cc.s

zone/chart_zone.o: zone/chart_zone.cc.o
.PHONY : zone/chart_zone.o

# target to build an object file
zone/chart_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/chart_zone.cc.o
.PHONY : zone/chart_zone.cc.o

zone/chart_zone.i: zone/chart_zone.cc.i
.PHONY : zone/chart_zone.i

# target to preprocess a source file
zone/chart_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/chart_zone.cc.i
.PHONY : zone/chart_zone.cc.i

zone/chart_zone.s: zone/chart_zone.cc.s
.PHONY : zone/chart_zone.s

# target to generate assembly for a file
zone/chart_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/chart_zone.cc.s
.PHONY : zone/chart_zone.cc.s

zone/check_list_zone.o: zone/check_list_zone.cc.o
.PHONY : zone/check_list_zone.o

# target to build an object file
zone/check_list_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/check_list_zone.cc.o
.PHONY : zone/check_list_zone.cc.o

zone/check_list_zone.i: zone/check_list_zone.cc.i
.PHONY : zone/check_list_zone.i

# target to preprocess a source file
zone/check_list_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/check_list_zone.cc.i
.PHONY : zone/check_list_zone.cc.i

zone/check_list_zone.s: zone/check_list_zone.cc.s
.PHONY : zone/check_list_zone.s

# target to generate assembly for a file
zone/check_list_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/check_list_zone.cc.s
.PHONY : zone/check_list_zone.cc.s

zone/creditcard_list_zone.o: zone/creditcard_list_zone.cc.o
.PHONY : zone/creditcard_list_zone.o

# target to build an object file
zone/creditcard_list_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/creditcard_list_zone.cc.o
.PHONY : zone/creditcard_list_zone.cc.o

zone/creditcard_list_zone.i: zone/creditcard_list_zone.cc.i
.PHONY : zone/creditcard_list_zone.i

# target to preprocess a source file
zone/creditcard_list_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/creditcard_list_zone.cc.i
.PHONY : zone/creditcard_list_zone.cc.i

zone/creditcard_list_zone.s: zone/creditcard_list_zone.cc.s
.PHONY : zone/creditcard_list_zone.s

# target to generate assembly for a file
zone/creditcard_list_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/creditcard_list_zone.cc.s
.PHONY : zone/creditcard_list_zone.cc.s

zone/dialog_zone.o: zone/dialog_zone.cc.o
.PHONY : zone/dialog_zone.o

# target to build an object file
zone/dialog_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/dialog_zone.cc.o
.PHONY : zone/dialog_zone.cc.o

zone/dialog_zone.i: zone/dialog_zone.cc.i
.PHONY : zone/dialog_zone.i

# target to preprocess a source file
zone/dialog_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/dialog_zone.cc.i
.PHONY : zone/dialog_zone.cc.i

zone/dialog_zone.s: zone/dialog_zone.cc.s
.PHONY : zone/dialog_zone.s

# target to generate assembly for a file
zone/dialog_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/dialog_zone.cc.s
.PHONY : zone/dialog_zone.cc.s

zone/drawer_zone.o: zone/drawer_zone.cc.o
.PHONY : zone/drawer_zone.o

# target to build an object file
zone/drawer_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/drawer_zone.cc.o
.PHONY : zone/drawer_zone.cc.o

zone/drawer_zone.i: zone/drawer_zone.cc.i
.PHONY : zone/drawer_zone.i

# target to preprocess a source file
zone/drawer_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/drawer_zone.cc.i
.PHONY : zone/drawer_zone.cc.i

zone/drawer_zone.s: zone/drawer_zone.cc.s
.PHONY : zone/drawer_zone.s

# target to generate assembly for a file
zone/drawer_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/drawer_zone.cc.s
.PHONY : zone/drawer_zone.cc.s

zone/expense_zone.o: zone/expense_zone.cc.o
.PHONY : zone/expense_zone.o

# target to build an object file
zone/expense_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/expense_zone.cc.o
.PHONY : zone/expense_zone.cc.o

zone/expense_zone.i: zone/expense_zone.cc.i
.PHONY : zone/expense_zone.i

# target to preprocess a source file
zone/expense_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/expense_zone.cc.i
.PHONY : zone/expense_zone.cc.i

zone/expense_zone.s: zone/expense_zone.cc.s
.PHONY : zone/expense_zone.s

# target to generate assembly for a file
zone/expense_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/expense_zone.cc.s
.PHONY : zone/expense_zone.cc.s

zone/form_zone.o: zone/form_zone.cc.o
.PHONY : zone/form_zone.o

# target to build an object file
zone/form_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/form_zone.cc.o
.PHONY : zone/form_zone.cc.o

zone/form_zone.i: zone/form_zone.cc.i
.PHONY : zone/form_zone.i

# target to preprocess a source file
zone/form_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/form_zone.cc.i
.PHONY : zone/form_zone.cc.i

zone/form_zone.s: zone/form_zone.cc.s
.PHONY : zone/form_zone.s

# target to generate assembly for a file
zone/form_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/form_zone.cc.s
.PHONY : zone/form_zone.cc.s

zone/hardware_zone.o: zone/hardware_zone.cc.o
.PHONY : zone/hardware_zone.o

# target to build an object file
zone/hardware_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/hardware_zone.cc.o
.PHONY : zone/hardware_zone.cc.o

zone/hardware_zone.i: zone/hardware_zone.cc.i
.PHONY : zone/hardware_zone.i

# target to preprocess a source file
zone/hardware_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/hardware_zone.cc.i
.PHONY : zone/hardware_zone.cc.i

zone/hardware_zone.s: zone/hardware_zone.cc.s
.PHONY : zone/hardware_zone.s

# target to generate assembly for a file
zone/hardware_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/hardware_zone.cc.s
.PHONY : zone/hardware_zone.cc.s

zone/inventory_zone.o: zone/inventory_zone.cc.o
.PHONY : zone/inventory_zone.o

# target to build an object file
zone/inventory_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/inventory_zone.cc.o
.PHONY : zone/inventory_zone.cc.o

zone/inventory_zone.i: zone/inventory_zone.cc.i
.PHONY : zone/inventory_zone.i

# target to preprocess a source file
zone/inventory_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/inventory_zone.cc.i
.PHONY : zone/inventory_zone.cc.i

zone/inventory_zone.s: zone/inventory_zone.cc.s
.PHONY : zone/inventory_zone.s

# target to generate assembly for a file
zone/inventory_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/inventory_zone.cc.s
.PHONY : zone/inventory_zone.cc.s

zone/labor_zone.o: zone/labor_zone.cc.o
.PHONY : zone/labor_zone.o

# target to build an object file
zone/labor_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/labor_zone.cc.o
.PHONY : zone/labor_zone.cc.o

zone/labor_zone.i: zone/labor_zone.cc.i
.PHONY : zone/labor_zone.i

# target to preprocess a source file
zone/labor_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/labor_zone.cc.i
.PHONY : zone/labor_zone.cc.i

zone/labor_zone.s: zone/labor_zone.cc.s
.PHONY : zone/labor_zone.s

# target to generate assembly for a file
zone/labor_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/labor_zone.cc.s
.PHONY : zone/labor_zone.cc.s

zone/layout_zone.o: zone/layout_zone.cc.o
.PHONY : zone/layout_zone.o

# target to build an object file
zone/layout_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/layout_zone.cc.o
.PHONY : zone/layout_zone.cc.o

zone/layout_zone.i: zone/layout_zone.cc.i
.PHONY : zone/layout_zone.i

# target to preprocess a source file
zone/layout_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/layout_zone.cc.i
.PHONY : zone/layout_zone.cc.i

zone/layout_zone.s: zone/layout_zone.cc.s
.PHONY : zone/layout_zone.s

# target to generate assembly for a file
zone/layout_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/layout_zone.cc.s
.PHONY : zone/layout_zone.cc.s

zone/login_zone.o: zone/login_zone.cc.o
.PHONY : zone/login_zone.o

# target to build an object file
zone/login_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/login_zone.cc.o
.PHONY : zone/login_zone.cc.o

zone/login_zone.i: zone/login_zone.cc.i
.PHONY : zone/login_zone.i

# target to preprocess a source file
zone/login_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/login_zone.cc.i
.PHONY : zone/login_zone.cc.i

zone/login_zone.s: zone/login_zone.cc.s
.PHONY : zone/login_zone.s

# target to generate assembly for a file
zone/login_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/login_zone.cc.s
.PHONY : zone/login_zone.cc.s

zone/merchant_zone.o: zone/merchant_zone.cc.o
.PHONY : zone/merchant_zone.o

# target to build an object file
zone/merchant_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/merchant_zone.cc.o
.PHONY : zone/merchant_zone.cc.o

zone/merchant_zone.i: zone/merchant_zone.cc.i
.PHONY : zone/merchant_zone.i

# target to preprocess a source file
zone/merchant_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/merchant_zone.cc.i
.PHONY : zone/merchant_zone.cc.i

zone/merchant_zone.s: zone/merchant_zone.cc.s
.PHONY : zone/merchant_zone.s

# target to generate assembly for a file
zone/merchant_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/merchant_zone.cc.s
.PHONY : zone/merchant_zone.cc.s

zone/order_zone.o: zone/order_zone.cc.o
.PHONY : zone/order_zone.o

# target to build an object file
zone/order_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/order_zone.cc.o
.PHONY : zone/order_zone.cc.o

zone/order_zone.i: zone/order_zone.cc.i
.PHONY : zone/order_zone.i

# target to preprocess a source file
zone/order_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/order_zone.cc.i
.PHONY : zone/order_zone.cc.i

zone/order_zone.s: zone/order_zone.cc.s
.PHONY : zone/order_zone.s

# target to generate assembly for a file
zone/order_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/order_zone.cc.s
.PHONY : zone/order_zone.cc.s

zone/payment_zone.o: zone/payment_zone.cc.o
.PHONY : zone/payment_zone.o

# target to build an object file
zone/payment_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payment_zone.cc.o
.PHONY : zone/payment_zone.cc.o

zone/payment_zone.i: zone/payment_zone.cc.i
.PHONY : zone/payment_zone.i

# target to preprocess a source file
zone/payment_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payment_zone.cc.i
.PHONY : zone/payment_zone.cc.i

zone/payment_zone.s: zone/payment_zone.cc.s
.PHONY : zone/payment_zone.s

# target to generate assembly for a file
zone/payment_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payment_zone.cc.s
.PHONY : zone/payment_zone.cc.s

zone/payout_zone.o: zone/payout_zone.cc.o
.PHONY : zone/payout_zone.o

# target to build an object file
zone/payout_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payout_zone.cc.o
.PHONY : zone/payout_zone.cc.o

zone/payout_zone.i: zone/payout_zone.cc.i
.PHONY : zone/payout_zone.i

# target to preprocess a source file
zone/payout_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payout_zone.cc.i
.PHONY : zone/payout_zone.cc.i

zone/payout_zone.s: zone/payout_zone.cc.s
.PHONY : zone/payout_zone.s

# target to generate assembly for a file
zone/payout_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/payout_zone.cc.s
.PHONY : zone/payout_zone.cc.s

zone/phrase_zone.o: zone/phrase_zone.cc.o
.PHONY : zone/phrase_zone.o

# target to build an object file
zone/phrase_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/phrase_zone.cc.o
.PHONY : zone/phrase_zone.cc.o

zone/phrase_zone.i: zone/phrase_zone.cc.i
.PHONY : zone/phrase_zone.i

# target to preprocess a source file
zone/phrase_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/phrase_zone.cc.i
.PHONY : zone/phrase_zone.cc.i

zone/phrase_zone.s: zone/phrase_zone.cc.s
.PHONY : zone/phrase_zone.s

# target to generate assembly for a file
zone/phrase_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/phrase_zone.cc.s
.PHONY : zone/phrase_zone.cc.s

zone/pos_zone.o: zone/pos_zone.cc.o
.PHONY : zone/pos_zone.o

# target to build an object file
zone/pos_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/pos_zone.cc.o
.PHONY : zone/pos_zone.cc.o

zone/pos_zone.i: zone/pos_zone.cc.i
.PHONY : zone/pos_zone.i

# target to preprocess a source file
zone/pos_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/pos_zone.cc.i
.PHONY : zone/pos_zone.cc.i

zone/pos_zone.s: zone/pos_zone.cc.s
.PHONY : zone/pos_zone.s

# target to generate assembly for a file
zone/pos_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/pos_zone.cc.s
.PHONY : zone/pos_zone.cc.s

zone/printer_zone.o: zone/printer_zone.cc.o
.PHONY : zone/printer_zone.o

# target to build an object file
zone/printer_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/printer_zone.cc.o
.PHONY : zone/printer_zone.cc.o

zone/printer_zone.i: zone/printer_zone.cc.i
.PHONY : zone/printer_zone.i

# target to preprocess a source file
zone/printer_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/printer_zone.cc.i
.PHONY : zone/printer_zone.cc.i

zone/printer_zone.s: zone/printer_zone.cc.s
.PHONY : zone/printer_zone.s

# target to generate assembly for a file
zone/printer_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/printer_zone.cc.s
.PHONY : zone/printer_zone.cc.s

zone/report_zone.o: zone/report_zone.cc.o
.PHONY : zone/report_zone.o

# target to build an object file
zone/report_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/report_zone.cc.o
.PHONY : zone/report_zone.cc.o

zone/report_zone.i: zone/report_zone.cc.i
.PHONY : zone/report_zone.i

# target to preprocess a source file
zone/report_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/report_zone.cc.i
.PHONY : zone/report_zone.cc.i

zone/report_zone.s: zone/report_zone.cc.s
.PHONY : zone/report_zone.s

# target to generate assembly for a file
zone/report_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/report_zone.cc.s
.PHONY : zone/report_zone.cc.s

zone/search_zone.o: zone/search_zone.cc.o
.PHONY : zone/search_zone.o

# target to build an object file
zone/search_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/search_zone.cc.o
.PHONY : zone/search_zone.cc.o

zone/search_zone.i: zone/search_zone.cc.i
.PHONY : zone/search_zone.i

# target to preprocess a source file
zone/search_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/search_zone.cc.i
.PHONY : zone/search_zone.cc.i

zone/search_zone.s: zone/search_zone.cc.s
.PHONY : zone/search_zone.s

# target to generate assembly for a file
zone/search_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/search_zone.cc.s
.PHONY : zone/search_zone.cc.s

zone/settings_zone.o: zone/settings_zone.cc.o
.PHONY : zone/settings_zone.o

# target to build an object file
zone/settings_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/settings_zone.cc.o
.PHONY : zone/settings_zone.cc.o

zone/settings_zone.i: zone/settings_zone.cc.i
.PHONY : zone/settings_zone.i

# target to preprocess a source file
zone/settings_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/settings_zone.cc.i
.PHONY : zone/settings_zone.cc.i

zone/settings_zone.s: zone/settings_zone.cc.s
.PHONY : zone/settings_zone.s

# target to generate assembly for a file
zone/settings_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/settings_zone.cc.s
.PHONY : zone/settings_zone.cc.s

zone/split_check_zone.o: zone/split_check_zone.cc.o
.PHONY : zone/split_check_zone.o

# target to build an object file
zone/split_check_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/split_check_zone.cc.o
.PHONY : zone/split_check_zone.cc.o

zone/split_check_zone.i: zone/split_check_zone.cc.i
.PHONY : zone/split_check_zone.i

# target to preprocess a source file
zone/split_check_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/split_check_zone.cc.i
.PHONY : zone/split_check_zone.cc.i

zone/split_check_zone.s: zone/split_check_zone.cc.s
.PHONY : zone/split_check_zone.s

# target to generate assembly for a file
zone/split_check_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/split_check_zone.cc.s
.PHONY : zone/split_check_zone.cc.s

zone/table_zone.o: zone/table_zone.cc.o
.PHONY : zone/table_zone.o

# target to build an object file
zone/table_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/table_zone.cc.o
.PHONY : zone/table_zone.cc.o

zone/table_zone.i: zone/table_zone.cc.i
.PHONY : zone/table_zone.i

# target to preprocess a source file
zone/table_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/table_zone.cc.i
.PHONY : zone/table_zone.cc.i

zone/table_zone.s: zone/table_zone.cc.s
.PHONY : zone/table_zone.s

# target to generate assembly for a file
zone/table_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/table_zone.cc.s
.PHONY : zone/table_zone.cc.s

zone/user_edit_zone.o: zone/user_edit_zone.cc.o
.PHONY : zone/user_edit_zone.o

# target to build an object file
zone/user_edit_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/user_edit_zone.cc.o
.PHONY : zone/user_edit_zone.cc.o

zone/user_edit_zone.i: zone/user_edit_zone.cc.i
.PHONY : zone/user_edit_zone.i

# target to preprocess a source file
zone/user_edit_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/user_edit_zone.cc.i
.PHONY : zone/user_edit_zone.cc.i

zone/user_edit_zone.s: zone/user_edit_zone.cc.s
.PHONY : zone/user_edit_zone.s

# target to generate assembly for a file
zone/user_edit_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/user_edit_zone.cc.s
.PHONY : zone/user_edit_zone.cc.s

zone/video_zone.o: zone/video_zone.cc.o
.PHONY : zone/video_zone.o

# target to build an object file
zone/video_zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/video_zone.cc.o
.PHONY : zone/video_zone.cc.o

zone/video_zone.i: zone/video_zone.cc.i
.PHONY : zone/video_zone.i

# target to preprocess a source file
zone/video_zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/video_zone.cc.i
.PHONY : zone/video_zone.cc.i

zone/video_zone.s: zone/video_zone.cc.s
.PHONY : zone/video_zone.s

# target to generate assembly for a file
zone/video_zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/video_zone.cc.s
.PHONY : zone/video_zone.cc.s

zone/zone.o: zone/zone.cc.o
.PHONY : zone/zone.o

# target to build an object file
zone/zone.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone.cc.o
.PHONY : zone/zone.cc.o

zone/zone.i: zone/zone.cc.i
.PHONY : zone/zone.i

# target to preprocess a source file
zone/zone.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone.cc.i
.PHONY : zone/zone.cc.i

zone/zone.s: zone/zone.cc.s
.PHONY : zone/zone.s

# target to generate assembly for a file
zone/zone.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone.cc.s
.PHONY : zone/zone.cc.s

zone/zone_object.o: zone/zone_object.cc.o
.PHONY : zone/zone_object.o

# target to build an object file
zone/zone_object.cc.o:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone_object.cc.o
.PHONY : zone/zone_object.cc.o

zone/zone_object.i: zone/zone_object.cc.i
.PHONY : zone/zone_object.i

# target to preprocess a source file
zone/zone_object.cc.i:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone_object.cc.i
.PHONY : zone/zone_object.cc.i

zone/zone_object.s: zone/zone_object.cc.s
.PHONY : zone/zone_object.s

# target to generate assembly for a file
zone/zone_object.cc.s:
	$(MAKE) -f CMakeFiles/zone.dir/build.make CMakeFiles/zone.dir/zone/zone_object.cc.s
.PHONY : zone/zone_object.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GenerateBuildNumber"
	@echo "... conf_file"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vt_cdu"
	@echo "... vt_main"
	@echo "... vt_print"
	@echo "... vt_temphash"
	@echo "... vt_term"
	@echo "... vtpos"
	@echo "... zone"
	@echo "... cdu/cdu_main.o"
	@echo "... cdu/cdu_main.i"
	@echo "... cdu/cdu_main.s"
	@echo "... conf_file.o"
	@echo "... conf_file.i"
	@echo "... conf_file.s"
	@echo "... data_file.o"
	@echo "... data_file.i"
	@echo "... data_file.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... external/blowfish.o"
	@echo "... external/blowfish.i"
	@echo "... external/blowfish.s"
	@echo "... external/sha1.o"
	@echo "... external/sha1.i"
	@echo "... external/sha1.s"
	@echo "... generic_char.o"
	@echo "... generic_char.i"
	@echo "... generic_char.s"
	@echo "... image_data.o"
	@echo "... image_data.i"
	@echo "... image_data.s"
	@echo "... loader/loader_main.o"
	@echo "... loader/loader_main.i"
	@echo "... loader/loader_main.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main/account.o"
	@echo "... main/account.i"
	@echo "... main/account.s"
	@echo "... main/archive.o"
	@echo "... main/archive.i"
	@echo "... main/archive.s"
	@echo "... main/cdu.o"
	@echo "... main/cdu.i"
	@echo "... main/cdu.s"
	@echo "... main/cdu_att.o"
	@echo "... main/cdu_att.i"
	@echo "... main/cdu_att.s"
	@echo "... main/chart.o"
	@echo "... main/chart.i"
	@echo "... main/chart.s"
	@echo "... main/check.o"
	@echo "... main/check.i"
	@echo "... main/check.s"
	@echo "... main/credit.o"
	@echo "... main/credit.i"
	@echo "... main/credit.s"
	@echo "... main/customer.o"
	@echo "... main/customer.i"
	@echo "... main/customer.s"
	@echo "... main/drawer.o"
	@echo "... main/drawer.i"
	@echo "... main/drawer.s"
	@echo "... main/employee.o"
	@echo "... main/employee.i"
	@echo "... main/employee.s"
	@echo "... main/exception.o"
	@echo "... main/exception.i"
	@echo "... main/exception.s"
	@echo "... main/expense.o"
	@echo "... main/expense.i"
	@echo "... main/expense.s"
	@echo "... main/inventory.o"
	@echo "... main/inventory.i"
	@echo "... main/inventory.s"
	@echo "... main/labels.o"
	@echo "... main/labels.i"
	@echo "... main/labels.s"
	@echo "... main/labor.o"
	@echo "... main/labor.i"
	@echo "... main/labor.s"
	@echo "... main/license.o"
	@echo "... main/license.i"
	@echo "... main/license.s"
	@echo "... main/license_hash.o"
	@echo "... main/license_hash.i"
	@echo "... main/license_hash.s"
	@echo "... main/locale.o"
	@echo "... main/locale.i"
	@echo "... main/locale.s"
	@echo "... main/manager.o"
	@echo "... main/manager.i"
	@echo "... main/manager.s"
	@echo "... main/printer.o"
	@echo "... main/printer.i"
	@echo "... main/printer.s"
	@echo "... main/report.o"
	@echo "... main/report.i"
	@echo "... main/report.s"
	@echo "... main/sales.o"
	@echo "... main/sales.i"
	@echo "... main/sales.s"
	@echo "... main/settings.o"
	@echo "... main/settings.i"
	@echo "... main/settings.s"
	@echo "... main/system.o"
	@echo "... main/system.i"
	@echo "... main/system.s"
	@echo "... main/system_report.o"
	@echo "... main/system_report.i"
	@echo "... main/system_report.s"
	@echo "... main/system_salesmix.o"
	@echo "... main/system_salesmix.i"
	@echo "... main/system_salesmix.s"
	@echo "... main/temphash.o"
	@echo "... main/temphash.i"
	@echo "... main/temphash.s"
	@echo "... main/terminal.o"
	@echo "... main/terminal.i"
	@echo "... main/terminal.s"
	@echo "... main/tips.o"
	@echo "... main/tips.i"
	@echo "... main/tips.s"
	@echo "... print/print_main.o"
	@echo "... print/print_main.i"
	@echo "... print/print_main.s"
	@echo "... remote_link.o"
	@echo "... remote_link.i"
	@echo "... remote_link.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... term/layer.o"
	@echo "... term/layer.i"
	@echo "... term/layer.s"
	@echo "... term/term_credit.o"
	@echo "... term/term_credit.i"
	@echo "... term/term_credit.s"
	@echo "... term/term_dialog.o"
	@echo "... term/term_dialog.i"
	@echo "... term/term_dialog.s"
	@echo "... term/term_main.o"
	@echo "... term/term_main.i"
	@echo "... term/term_main.s"
	@echo "... term/term_view.o"
	@echo "... term/term_view.i"
	@echo "... term/term_view.s"
	@echo "... term/touch_screen.o"
	@echo "... term/touch_screen.i"
	@echo "... term/touch_screen.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
	@echo "... zone/account_zone.o"
	@echo "... zone/account_zone.i"
	@echo "... zone/account_zone.s"
	@echo "... zone/button_zone.o"
	@echo "... zone/button_zone.i"
	@echo "... zone/button_zone.s"
	@echo "... zone/cdu_zone.o"
	@echo "... zone/cdu_zone.i"
	@echo "... zone/cdu_zone.s"
	@echo "... zone/chart_zone.o"
	@echo "... zone/chart_zone.i"
	@echo "... zone/chart_zone.s"
	@echo "... zone/check_list_zone.o"
	@echo "... zone/check_list_zone.i"
	@echo "... zone/check_list_zone.s"
	@echo "... zone/creditcard_list_zone.o"
	@echo "... zone/creditcard_list_zone.i"
	@echo "... zone/creditcard_list_zone.s"
	@echo "... zone/dialog_zone.o"
	@echo "... zone/dialog_zone.i"
	@echo "... zone/dialog_zone.s"
	@echo "... zone/drawer_zone.o"
	@echo "... zone/drawer_zone.i"
	@echo "... zone/drawer_zone.s"
	@echo "... zone/expense_zone.o"
	@echo "... zone/expense_zone.i"
	@echo "... zone/expense_zone.s"
	@echo "... zone/form_zone.o"
	@echo "... zone/form_zone.i"
	@echo "... zone/form_zone.s"
	@echo "... zone/hardware_zone.o"
	@echo "... zone/hardware_zone.i"
	@echo "... zone/hardware_zone.s"
	@echo "... zone/inventory_zone.o"
	@echo "... zone/inventory_zone.i"
	@echo "... zone/inventory_zone.s"
	@echo "... zone/labor_zone.o"
	@echo "... zone/labor_zone.i"
	@echo "... zone/labor_zone.s"
	@echo "... zone/layout_zone.o"
	@echo "... zone/layout_zone.i"
	@echo "... zone/layout_zone.s"
	@echo "... zone/login_zone.o"
	@echo "... zone/login_zone.i"
	@echo "... zone/login_zone.s"
	@echo "... zone/merchant_zone.o"
	@echo "... zone/merchant_zone.i"
	@echo "... zone/merchant_zone.s"
	@echo "... zone/order_zone.o"
	@echo "... zone/order_zone.i"
	@echo "... zone/order_zone.s"
	@echo "... zone/payment_zone.o"
	@echo "... zone/payment_zone.i"
	@echo "... zone/payment_zone.s"
	@echo "... zone/payout_zone.o"
	@echo "... zone/payout_zone.i"
	@echo "... zone/payout_zone.s"
	@echo "... zone/phrase_zone.o"
	@echo "... zone/phrase_zone.i"
	@echo "... zone/phrase_zone.s"
	@echo "... zone/pos_zone.o"
	@echo "... zone/pos_zone.i"
	@echo "... zone/pos_zone.s"
	@echo "... zone/printer_zone.o"
	@echo "... zone/printer_zone.i"
	@echo "... zone/printer_zone.s"
	@echo "... zone/report_zone.o"
	@echo "... zone/report_zone.i"
	@echo "... zone/report_zone.s"
	@echo "... zone/search_zone.o"
	@echo "... zone/search_zone.i"
	@echo "... zone/search_zone.s"
	@echo "... zone/settings_zone.o"
	@echo "... zone/settings_zone.i"
	@echo "... zone/settings_zone.s"
	@echo "... zone/split_check_zone.o"
	@echo "... zone/split_check_zone.i"
	@echo "... zone/split_check_zone.s"
	@echo "... zone/table_zone.o"
	@echo "... zone/table_zone.i"
	@echo "... zone/table_zone.s"
	@echo "... zone/user_edit_zone.o"
	@echo "... zone/user_edit_zone.i"
	@echo "... zone/user_edit_zone.s"
	@echo "... zone/video_zone.o"
	@echo "... zone/video_zone.i"
	@echo "... zone/video_zone.s"
	@echo "... zone/zone.o"
	@echo "... zone/zone.i"
	@echo "... zone/zone.s"
	@echo "... zone/zone_object.o"
	@echo "... zone/zone_object.i"
	@echo "... zone/zone_object.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

