#!/bin/sh

MAXROTATES=5
HOSTNAME=`hostname -s`
FILENAME=viewtouch-$HOSTNAME-backup.tar.gz

function rotate () {
    MAX=$1 ; shift
    FILE=$1 ; shift
    NUM=$MAX
    if [ -f $FILE ] ; then
        while [ $NUM -gt 0 ] ; do
            if [ $NUM -eq $MAX ] ; then
                if [ -f $FILE.$NUM ] ; then
                    rm $FILE.$NUM
                fi
            elif [ -f $FILE.$NUM ] ; then
                NEXT=$(($NUM + 1))
                mv $FILE.$NUM $FILE.$NEXT
            fi
            NUM=$(($NUM - 1))
        done
        mv $FILE $FILE.1
    fi
}


rotate $MAXROTATES $FILENAME
tar czf $FILENAME /usr/viewtouch/dat >/dev/null 2>&1
