#!/bin/sh

WGET=`which wget`
CURL=`which curl`
LICENSE=/usr/viewtouch/dat/.viewtouch_license
URL='http://www.viewtouch.com/cgi-bin/vt_check_license.cgi?ping=1&hwid='
HWID=`cat $LICENSE | grep '^digest' | awk '{print $2}'`

if [ -n "$WGET" -a -f $WGET ]; then
	$WGET -q -O /dev/null $URL$HWID
elif [ -n "$CURL" -a -f $CURL ]; then
	$CURL -o /dev/null -s $URL$HWID
fi

