#!/usr/bin/perl -w

# ####################################################################
# INITIALIZATION AND GLOBAL VARIABLES
# ####################################################################
use strict;

my $tarbin = `which tar`;  chomp( $tarbin );
my $uubin  = `which uuencode`; chomp( $uubin );

my $pwd = `pwd`; chomp( $pwd );
my $vt_install  = "$pwd/scripts/vt_install";
chdir("/usr/viewtouch/release");
my $vt_bin_path = "/usr/viewtouch/bin";
my $vt_dat_path = "usr/viewtouch/dat";
my $system_name = `uname`;
chomp( $system_name );
my $date_string = `date +"%b-%d-%Y-%H%M"`;
chomp( $date_string );
my $credit_name = ( $ARGV[0] ? "-".$ARGV[0] : "" );

my $installer = "$ENV{'HOME'}/tmp/viewtouch-installer".$credit_name."-".$system_name."-".$date_string.".pl";

my @binfiles = ( "$vt_bin_path/vtpos",
                 "$vt_bin_path/vt_main",
                 "$vt_bin_path/vt_term",
                 "$vt_bin_path/vt_print",
                 "$vt_bin_path/vt_cdu",
                 "$vt_bin_path/vtrestart",
                 "$vt_bin_path/vtrun",
                 "$vt_bin_path/vtcommands",
                 "$vt_bin_path/keeprunning",
                 "$vt_bin_path/keeprunningcron",
                 "$vt_bin_path/vt_ccq_pipe",
                 "$vt_bin_path/vt_ping",
                 "$vt_bin_path/vt_pingcheck",
                 "$vt_bin_path/vt_shutdown",
                 "$vt_bin_path/vt_openterm",
                 "$vt_bin_path/update-client",
                 "$vt_bin_path/usercount",
                 "$vt_bin_path/lpd-restart",
                 "$vt_bin_path/ChangeLog" );
chomp(@binfiles);
my $binfiles = join(" ", @binfiles);
my $binname  = "viewtouch_binaries";

my $vt_data = ( -f "$vt_dat_path/vt_data" ? "$vt_dat_path/vt_data" : "$vt_bin_path/vt_data" );
my @datfiles  = ( "$vt_data",
                  "$vt_dat_path/*.dat",
                  "$vt_dat_path/screensaver",
                  "$vt_dat_path/languages",
                  "$vt_dat_path/text" );
chomp(@datfiles);
my $datfiles = join(" ", @datfiles);
my $datname  = "viewtouch_data";


# ####################################################################
# MAIN LOOP
# ####################################################################
my $binaries  = getFiles( $binfiles, $binname );
my $data      = getFiles( $datfiles, $datname );
my $changelog = `/bin/cat $vt_bin_path/ChangeLog`;

my $file = "";
if ( open( FILE, "$vt_install" ) ) {
    $file = join( "", <FILE> );
    close( FILE );
    
    $file =~ s/!!!BINFILE!!!/$binaries/gs;
    $file =~ s/!!!DATFILE!!!/$data/gs;
    $file =~ s/!!!CHANGELOG!!!/$changelog/gs;
    
    if ( open( FILE, ">$installer" ) ) {
        print FILE $file;
        close( FILE );
        system( "chmod 0755 $installer" );
    }
} else {
    print STDERR "ERROR:  Cannot find vt_install script!!!!\n";
}


# ####################################################################
# SUBROUTINES
# ####################################################################

sub getFiles {
    my ( $files, $uuname ) = @_;
    my $arc = `$tarbin czf - $files | $uubin $uuname 2>/dev/null`;
    return( $arc );
}
