#!/usr/bin/perl -w

use strict;

foreach ( @ARGV ) {
    next if ( $_ =~ /^\./ );
    next if ( $_ =~ /^\s*$/ );
    my $file = $_;
    print "Processing $file...\n";
    ProcessFile( $file );
}

sub ReadFile {
    my ( $file ) = @_;
    my @contents;

    if ( open( FILE, $file ) ) {
        @contents = <FILE>;
        close( FILE );
    }

    return( \@contents );
}

sub WriteFile {
    my ( $file, $contents ) = @_;
    my $retval = 0;

    if ( open( FILE, ">".$file ) ) {
        foreach ( @$contents ) {
            print FILE $_;
            if ( $_ !~ /\n$/s ) {
                print FILE "\n";
            }
        }
        $retval = 1;
        close( FILE );
    } else {
        print STDERR "  Unable to write $file:  $!\n";
    }

    return( $retval );
}

sub ShowFile {
    my ( $contents ) = @_;

    foreach ( @$contents ) {
        print $_;
        if ( $_ !~ /\n$/s ) {
            print "\n";
        }
    }
}

sub MakePayment {
    my @now = localtime( time() );
    my $day  = $now[3];
    my $mon  = $now[4] + 1;
    my $year = $now[5] + 1900;

    $day = "0" . $day if ( $day < 10 );
    $mon = "0" . $mon if ( $mon < 10 );

    my $payment = "  $day/$mon/$year    0.00";
    return( $payment );
}

sub ProcessFile {
    my ( $file ) = @_;
    my $retval = 0;
    my $have_payments = 0;
    my $contents = ReadFile( $file );
    my @newcontents;

    foreach ( @$contents ) {
        my $line = $_;
        next if ( $line =~ /^\s*$/ );
        if ( $have_payments && $line =~ /^\s+/ ) {
        } elsif ( $line =~ /^Payment History/ ) {
            push( @newcontents, $line );
            $have_payments = 1;
        } else {
            push( @newcontents, $line );
        }
    }
    if ( $have_payments ) {
        push( @newcontents, MakePayment() );
        WriteFile( $file, \@newcontents );
    }

    return( $retval );
}
