#!/bin/sh

LOGDIR=$1
shift
RUNDIR=$1
shift

if [ -z "$LOGDIR" ]; then
    echo "Usage:  $0"' <log directory> <run directory> <command [arg1 .. [argN]]>'
    echo
    exit
fi

COMMAND=$1
shift
SCOMM=`basename $COMMAND`
COMMAND="$COMMAND $*"
LOG=$LOGDIR/keeprunning.$SCOMM.log
RUN=$RUNDIR/keeprunning.$SCOMM.pid

if [ ! -f "$RUN" ]; then
    echo Starting $SCOMM, no run file
    $COMMAND >>$LOG 2>&1 &
    echo $! >$RUN
else
    PID=`cat $RUN`
    if [ -z "`ps ax | grep $PID | grep -v grep`" ]; then
        echo Starting $SCOMM ...
        $COMMAND >>$LOG 2>&1 &
        echo $! >$RUN
    fi
fi
