#!/bin/sh

LOGDIR=$1
shift

if [ -z "$LOGDIR" ]; then
    echo "Usage:  $0"' <log directory> <command [arg1 .. [argN]]>'
    echo
    exit
fi

COMMAND=$*
SCOMM=`basename $COMMAND`
LOG=$LOGDIR/keeprunning.$SCOMM.log

if [ -n "$SCOMM" ]; then
    killall "$SCOMM"
fi

while [ -n "$COMMAND" ]
do
    $COMMAND >>$LOG 2>&1 &
    PID=$!
    while [ -n "`ps ax | grep "$PID" | grep -v grep`" ]
    do
        sleep 5
    done
done
