#!/bin/bash
process=vt_main  # What do we want to run once or kill?
t=`pidof $process`       # Find pid (process id) of $process.
# The pid is needed by 'kill' (can't 'kill' by program name).

if [ -z "$t" ]           # If process not present, 'pidof' returns null.
then
  date >> /usr/viewtouch/dat/runlog
  echo "ViewTouch was not running, starting now" >> /usr/viewtouch/dat/runlog
  date >> /usr/viewtouch/dat/debuglog
  /usr/viewtouch/bin/vtpos >> /usr/viewtouch/dat/debuglog 2>&1 &
  exit 0
fi

  date >> /usr/viewtouch/dat/runlog
  echo $t >> /usr/viewtouch/dat/runlog
  echo "Maximizing ViewTouch" >> /usr/viewtouch/dat/runlog
xwit -pop -names 'View'
exit 0


