#!/bin/sh

VTPATH=$1
VTPOS=`cat $VTPATH/bin/.vtpos_command`
VTRESTART=$VTPATH/dat/.restart_flag

while [ ! -f $VTRESTART ];
do
	sleep 3
done

rm $VTRESTART
export DISPLAY=:0 # Fix: Ensure X11 display is set before launching vtpos
exec $VTPOS


